### ISSUE TITLE
/help and /contact not working

### ISSUE THREAD

**Issue by suhasa010** [CrushFam/BookCrushBot#1]
Issue: the following commands are not working as expected.

Actual output: /help ???
Sorry I did not get it.

Expected output: help info for /help and contact info for /contact.

**Comment by arun-mani-j** [comment]
Thanks for the report, now we are removing the "bug report" feature.

JK :joy:
Fixed.

**Comment by suhasa010** [comment]
> Thanks for the report, now we are removing the "bug report" feature.
> 
> JK :joy:
> Fixed. 

I'll raise a bug to reopen the bug report feature 😈😂
