### ISSUE TITLE
Enhancement: showing the current botm, current roulette book, current month's schedule

### ISSUE THREAD

**Issue by suhasa010** [CrushFam/BookCrushBot#3]
Title says it all. ;)

**Comment by arun-mani-j** [comment]
This is not a big deal. The welcome message (the message shown for /start) is taken from [START.md](https://github.com/CrushFam/BookCrushBot/blob/master/data/START.md). So we can change it every month to reflect the current schedule.

Patches welcome for START.md . 
^^
